#!/bin/bash

# Exit on failiure(including ERR trap), exit on unset variables,
# print each command, piping non-zero exit code also exits
set -Eeuxo pipefail


if [ "${DJANGO_SETTINGS_MODULE}" != "config.settings.local" ]; then
  python compose/local/django/get_credentials.py
  set -a
  source .source
  set +a
fi


if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

postgres_ready() {
  python compose/local/django/check_postgres_conn.py
}

until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
