#!/bin/bash

# Exit on failiure(including ERR trap), exit on unset variables,
# print each command, piping non-zero exit code also exits
set -Eeuxo pipefail

python manage.py migrate
python manage.py runserver 0.0.0.0:8000
