# Generated by Django 2.2.5 on 2020-09-13 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0003_auto_20200913_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hat', models.PositiveSmallIntegerField(default=0)),
                ('face', models.PositiveSmallIntegerField(default=0)),
                ('skin', models.PositiveSmallIntegerField(default=0)),
                ('shirt', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('player_type', models.PositiveIntegerField(choices=[(0, 'player'), (1, 'spectator')], default=1)),
                ('is_admin', models.BooleanField(default=False)),
                ('avatar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.Avatar')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sessions.Session')),
            ],
        ),
    ]
